spring:
  application:
    name: main-server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # 데이터베이스 설정 (PostgreSQL)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ddobak_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:ddobak_user}
    password: ${DB_PASSWORD:your_password}

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # DB 스키마 자동 생성
    properties:
      hibernate:
        show-sql: true  # 쿼리 로그 출력
        format_sql: true  # 쿼리 로그 포맷 (정렬)
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 서버 설정
server:
  port: 8080

# JWT 설정
jwt:
  secret: secret-key-for-jwt-token
  expiration: 86400000 # 24시간 (밀리초)

# 로깅 설정
logging:
  level:
    com.sbpb.ddobak.server.common.utils.LambdaUtil: DEBUG
    com.sbpb.ddobak.server.domain.documentProcess.service.DocumentProcessService: DEBUG

# AWS 설정
aws:
  region: ap-northeast-2
  profile: ddobak
  s3:
    test-bucket: ddobak-test  # 테스트용 버킷
    service-bucket: ${SERVICE_BUCKET:ddobak-test}  # 서비스용 버킷
  lambda:
    ocr-function-name: ocr_lambda
    analysis-function-name: bedrock_lambda
