name: Deploy to EC2

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build with Gradle
      run: ./gradlew clean bootJar -x test
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          # 프로젝트 디렉토리로 이동
          cd /home/ec2-user/DDOBAK-Backend-Core
          
          # Git pull로 최신 코드 가져오기
          git fetch origin
          git reset --hard origin/dev
          
          # 기존 서버 중지
          pkill -f "java -jar" || true
          sleep 5
          
          # 빌드
          ./gradlew clean bootJar -x test
          
          # AWS 자격 증명 확인
          echo "=== AWS Credentials Check ==="
          aws sts get-caller-identity
          
          # 서버 재시작
          nohup java -jar build/libs/main-server-0.0.1-SNAPSHOT.jar > server.log 2>&1 &
          
          # 서버 상태 확인
          sleep 15
          echo "=== Server Process Check ==="
          ps aux | grep java
          
          echo "=== Port Check ==="
          netstat -tlnp | grep 8080
          
          echo "=== Server Log Check ==="
          tail -10 server.log
          
          echo "Github Actions를 통한 EC2 배포 성공!" 